spring:
  application:
    name: rag-redis
  ai:
    vectorstore:
      redis:
        uri: redis://localhost:9736
        index: rag-index
        prefix: "rag:"
        initialize-schema: true
    ollama:
      chat:
        options:
          model: llama3.1:8b
      embedding:
        model: llama3.1:8b
  docker:
    compose:
      lifecycle-management: start_only

server:
  port: 7772
