spring:
  application:
    name: rag-redis
  data:
    redis:
      url: redis://localhost:9736
  ai:
    vectorstore:
      redis:
        prefix: "rag:"
        initialize-schema: true
        index-name: rag-index
    ollama:
      chat:
        options:
          model: llama3.1:8b
      embedding:
        model: llama3.1:8b
  docker:
    compose:
      lifecycle-management: start_only

server:
  port: 7772
