spring.ai.mcp.server.name: mcp-server-graphql
spring.ai.mcp.server.version: 0.0.1
server.port: 7004
spring:
  ai:
    mcp:
      server:
        type: async

graphql:
  schemas:
    - "http://localhost:11180/schema.graphql"
