spring.ai.mcp.server.name: mcp-server-petstore
spring.ai.mcp.server.version: 0.0.1
server.port: 7002
spring:
  ai:
    mcp:
      server:
        type: async

openapi:
  urls:
    - "http://localhost:8334/openapi.yaml"

spring.profiles.active: local

management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true

---
spring.config.activate.on-profile: docker
server.port: 80
