spring:
  application:
    name: mcp-openapi-chat
  ai:
    ollama:
      chat:
        options:
          model: llama3.1:8b
    mcp:
      client:
        type: async
        sse:
          connections:
            mcp-server-petstore:
              url: http://localhost:7002

server:
  port: 7775

spring.profiles.active: local
