spring:
  application:
    name: mcp-openapi-chat
  ai:
    ollama:
      chat:
        options:
          model: llama3.1:8b
    mcp:
      client:
        type: async
        sse:
          connections:
            mcp-server-petstore:
              url: http://localhost:7002
            mcp-server-samples:
              url: http://localhost:7003

server:
  port: 7775

spring.profiles.active: local

management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true

---
spring.config.activate.on-profile: docker
server.port: 80
